import '../node_modules/normalize.css/normalize.css';
import './components/modal/modalBackDrop.js';
import './styles.css';
import './components/footer/styles.js';
import './components/header/js/header';
import './components/hero/slider-item/slider-item';
import './components/card/index';
import './components/loader/index';
// import './components/auth/auth';
import './components/developers/js/index';
import './components/developers/modal-window/dev-modal';
import './components/developers/modal-window/dev-styles.css';
import './components/modal/modalBackDrop.js';
